title:              Sunio Dev Blog
email:              sunio00000@naver.com
description:        A Blog Theme by Start Bootstrap
author:             Sunio
baseurl:            "https://sunio00000.github.io"
url:                "https://sunio00000.github.io"

# Social Profiles
twitter_username:   sunio00000
github_username:    sunio00000
facebook_username:  sunio00000
linkedin_username:  sunio00000

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
